// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/quartetfs.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Upload Messages (Unchanged) ---
type ChunkUploadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeAddresses []string               `protobuf:"bytes,1,rep,name=node_addresses,json=nodeAddresses,proto3" json:"node_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadInfo) Reset() {
	*x = ChunkUploadInfo{}
	mi := &file_api_quartetfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadInfo) ProtoMessage() {}

func (x *ChunkUploadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadInfo.ProtoReflect.Descriptor instead.
func (*ChunkUploadInfo) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkUploadInfo) GetNodeAddresses() []string {
	if x != nil {
		return x.NodeAddresses
	}
	return nil
}

type InitiateUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FilesizeBytes int64                  `protobuf:"varint,2,opt,name=filesize_bytes,json=filesizeBytes,proto3" json:"filesize_bytes,omitempty"`
	ChunkHashes   []string               `protobuf:"bytes,3,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateUploadRequest) Reset() {
	*x = InitiateUploadRequest{}
	mi := &file_api_quartetfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateUploadRequest) ProtoMessage() {}

func (x *InitiateUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateUploadRequest.ProtoReflect.Descriptor instead.
func (*InitiateUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InitiateUploadRequest) GetFilesizeBytes() int64 {
	if x != nil {
		return x.FilesizeBytes
	}
	return 0
}

func (x *InitiateUploadRequest) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type InitiateUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadPlan    *ChunkUploadInfo       `protobuf:"bytes,2,opt,name=upload_plan,json=uploadPlan,proto3" json:"upload_plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateUploadResponse) Reset() {
	*x = InitiateUploadResponse{}
	mi := &file_api_quartetfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateUploadResponse) ProtoMessage() {}

func (x *InitiateUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateUploadResponse.ProtoReflect.Descriptor instead.
func (*InitiateUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{2}
}

func (x *InitiateUploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *InitiateUploadResponse) GetUploadPlan() *ChunkUploadInfo {
	if x != nil {
		return x.UploadPlan
	}
	return nil
}

type FinalizeUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkHashes   []string               `protobuf:"bytes,2,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeUploadRequest) Reset() {
	*x = FinalizeUploadRequest{}
	mi := &file_api_quartetfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeUploadRequest) ProtoMessage() {}

func (x *FinalizeUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeUploadRequest.ProtoReflect.Descriptor instead.
func (*FinalizeUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{3}
}

func (x *FinalizeUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FinalizeUploadRequest) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type FinalizeUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeUploadResponse) Reset() {
	*x = FinalizeUploadResponse{}
	mi := &file_api_quartetfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeUploadResponse) ProtoMessage() {}

func (x *FinalizeUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeUploadResponse.ProtoReflect.Descriptor instead.
func (*FinalizeUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{4}
}

func (x *FinalizeUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StoreChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHash     string                 `protobuf:"bytes,1,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreChunkRequest) Reset() {
	*x = StoreChunkRequest{}
	mi := &file_api_quartetfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreChunkRequest) ProtoMessage() {}

func (x *StoreChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreChunkRequest.ProtoReflect.Descriptor instead.
func (*StoreChunkRequest) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{5}
}

func (x *StoreChunkRequest) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *StoreChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StoreChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreChunkResponse) Reset() {
	*x = StoreChunkResponse{}
	mi := &file_api_quartetfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreChunkResponse) ProtoMessage() {}

func (x *StoreChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreChunkResponse.ProtoReflect.Descriptor instead.
func (*StoreChunkResponse) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{6}
}

func (x *StoreChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreChunkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Download Messages - NEW! ---
type DownloadLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadLocationsRequest) Reset() {
	*x = DownloadLocationsRequest{}
	mi := &file_api_quartetfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadLocationsRequest) ProtoMessage() {}

func (x *DownloadLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadLocationsRequest.ProtoReflect.Descriptor instead.
func (*DownloadLocationsRequest) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadLocationsRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type ChunkDownloadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHash     string                 `protobuf:"bytes,1,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	NodeAddresses []string               `protobuf:"bytes,2,rep,name=node_addresses,json=nodeAddresses,proto3" json:"node_addresses,omitempty"` // Nodes that have this chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkDownloadInfo) Reset() {
	*x = ChunkDownloadInfo{}
	mi := &file_api_quartetfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkDownloadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkDownloadInfo) ProtoMessage() {}

func (x *ChunkDownloadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkDownloadInfo.ProtoReflect.Descriptor instead.
func (*ChunkDownloadInfo) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkDownloadInfo) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *ChunkDownloadInfo) GetNodeAddresses() []string {
	if x != nil {
		return x.NodeAddresses
	}
	return nil
}

type DownloadLocationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of all chunks needed for the file and where to find them.
	ChunkLocations []*ChunkDownloadInfo `protobuf:"bytes,1,rep,name=chunk_locations,json=chunkLocations,proto3" json:"chunk_locations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DownloadLocationsResponse) Reset() {
	*x = DownloadLocationsResponse{}
	mi := &file_api_quartetfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadLocationsResponse) ProtoMessage() {}

func (x *DownloadLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadLocationsResponse.ProtoReflect.Descriptor instead.
func (*DownloadLocationsResponse) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadLocationsResponse) GetChunkLocations() []*ChunkDownloadInfo {
	if x != nil {
		return x.ChunkLocations
	}
	return nil
}

type GetChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHash     string                 `protobuf:"bytes,1,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_api_quartetfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{10}
}

func (x *GetChunkRequest) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

type GetChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_api_quartetfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_quartetfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_api_quartetfs_proto_rawDescGZIP(), []int{11}
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_quartetfs_proto protoreflect.FileDescriptor

const file_api_quartetfs_proto_rawDesc = "" +
	"\n" +
	"\x13api/quartetfs.proto\x12\x03api\"8\n" +
	"\x0fChunkUploadInfo\x12%\n" +
	"\x0enode_addresses\x18\x01 \x03(\tR\rnodeAddresses\"}\n" +
	"\x15InitiateUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12%\n" +
	"\x0efilesize_bytes\x18\x02 \x01(\x03R\rfilesizeBytes\x12!\n" +
	"\fchunk_hashes\x18\x03 \x03(\tR\vchunkHashes\"h\n" +
	"\x16InitiateUploadResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x125\n" +
	"\vupload_plan\x18\x02 \x01(\v2\x14.api.ChunkUploadInfoR\n" +
	"uploadPlan\"S\n" +
	"\x15FinalizeUploadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12!\n" +
	"\fchunk_hashes\x18\x02 \x03(\tR\vchunkHashes\"2\n" +
	"\x16FinalizeUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x11StoreChunkRequest\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x01 \x01(\tR\tchunkHash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"H\n" +
	"\x12StoreChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x18DownloadLocationsRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"Y\n" +
	"\x11ChunkDownloadInfo\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x01 \x01(\tR\tchunkHash\x12%\n" +
	"\x0enode_addresses\x18\x02 \x03(\tR\rnodeAddresses\"\\\n" +
	"\x19DownloadLocationsResponse\x12?\n" +
	"\x0fchunk_locations\x18\x01 \x03(\v2\x16.api.ChunkDownloadInfoR\x0echunkLocations\"0\n" +
	"\x0fGetChunkRequest\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x01 \x01(\tR\tchunkHash\"&\n" +
	"\x10GetChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xfe\x01\n" +
	"\x0fMetadataService\x12I\n" +
	"\x0eInitiateUpload\x12\x1a.api.InitiateUploadRequest\x1a\x1b.api.InitiateUploadResponse\x12I\n" +
	"\x0eFinalizeUpload\x12\x1a.api.FinalizeUploadRequest\x1a\x1b.api.FinalizeUploadResponse\x12U\n" +
	"\x14GetDownloadLocations\x12\x1d.api.DownloadLocationsRequest\x1a\x1e.api.DownloadLocationsResponse2\x8c\x01\n" +
	"\x12StorageNodeService\x12=\n" +
	"\n" +
	"StoreChunk\x12\x16.api.StoreChunkRequest\x1a\x17.api.StoreChunkResponse\x127\n" +
	"\bGetChunk\x12\x14.api.GetChunkRequest\x1a\x15.api.GetChunkResponseB\aZ\x05./apib\x06proto3"

var (
	file_api_quartetfs_proto_rawDescOnce sync.Once
	file_api_quartetfs_proto_rawDescData []byte
)

func file_api_quartetfs_proto_rawDescGZIP() []byte {
	file_api_quartetfs_proto_rawDescOnce.Do(func() {
		file_api_quartetfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_quartetfs_proto_rawDesc), len(file_api_quartetfs_proto_rawDesc)))
	})
	return file_api_quartetfs_proto_rawDescData
}

var file_api_quartetfs_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_quartetfs_proto_goTypes = []any{
	(*ChunkUploadInfo)(nil),           // 0: api.ChunkUploadInfo
	(*InitiateUploadRequest)(nil),     // 1: api.InitiateUploadRequest
	(*InitiateUploadResponse)(nil),    // 2: api.InitiateUploadResponse
	(*FinalizeUploadRequest)(nil),     // 3: api.FinalizeUploadRequest
	(*FinalizeUploadResponse)(nil),    // 4: api.FinalizeUploadResponse
	(*StoreChunkRequest)(nil),         // 5: api.StoreChunkRequest
	(*StoreChunkResponse)(nil),        // 6: api.StoreChunkResponse
	(*DownloadLocationsRequest)(nil),  // 7: api.DownloadLocationsRequest
	(*ChunkDownloadInfo)(nil),         // 8: api.ChunkDownloadInfo
	(*DownloadLocationsResponse)(nil), // 9: api.DownloadLocationsResponse
	(*GetChunkRequest)(nil),           // 10: api.GetChunkRequest
	(*GetChunkResponse)(nil),          // 11: api.GetChunkResponse
}
var file_api_quartetfs_proto_depIdxs = []int32{
	0,  // 0: api.InitiateUploadResponse.upload_plan:type_name -> api.ChunkUploadInfo
	8,  // 1: api.DownloadLocationsResponse.chunk_locations:type_name -> api.ChunkDownloadInfo
	1,  // 2: api.MetadataService.InitiateUpload:input_type -> api.InitiateUploadRequest
	3,  // 3: api.MetadataService.FinalizeUpload:input_type -> api.FinalizeUploadRequest
	7,  // 4: api.MetadataService.GetDownloadLocations:input_type -> api.DownloadLocationsRequest
	5,  // 5: api.StorageNodeService.StoreChunk:input_type -> api.StoreChunkRequest
	10, // 6: api.StorageNodeService.GetChunk:input_type -> api.GetChunkRequest
	2,  // 7: api.MetadataService.InitiateUpload:output_type -> api.InitiateUploadResponse
	4,  // 8: api.MetadataService.FinalizeUpload:output_type -> api.FinalizeUploadResponse
	9,  // 9: api.MetadataService.GetDownloadLocations:output_type -> api.DownloadLocationsResponse
	6,  // 10: api.StorageNodeService.StoreChunk:output_type -> api.StoreChunkResponse
	11, // 11: api.StorageNodeService.GetChunk:output_type -> api.GetChunkResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_quartetfs_proto_init() }
func file_api_quartetfs_proto_init() {
	if File_api_quartetfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_quartetfs_proto_rawDesc), len(file_api_quartetfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_quartetfs_proto_goTypes,
		DependencyIndexes: file_api_quartetfs_proto_depIdxs,
		MessageInfos:      file_api_quartetfs_proto_msgTypes,
	}.Build()
	File_api_quartetfs_proto = out.File
	file_api_quartetfs_proto_goTypes = nil
	file_api_quartetfs_proto_depIdxs = nil
}
